spring.application.name=SpringBootMSProj14MiniProject-ConfigServerApplication

#providing embedded server port number
server.port=8888

#Providing the link where the project is created in gitlab account
spring.cloud.config.server.git.uri=https://gitlab.com/eshwart438-group/eshwart438-configserverproj.git

spring.cloud.config.server.git.default-label=main

#registration url of eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#specifying Logger File name
logging.file.name=c:/MicroServiceMiniProject/config_elk_log2.txt

#specifying the logger level as debug for com.eshwar(root package) package
logging.level.com.eshwar=DEBUG

#activate all actuators
management.endpoints.web.exposure.include=*






