spring.application.name=ORDER-SERVICE
#this tells to connect to the config server which is running on the 8888 port no
spring.config.import=optional:configserver:http://localhost:8888

#specifying Logger File name
logging.file.name=c:/MicroServiceMiniProject/order-service_log8.txt

#specifying the logger level as debug for com.eshwar(root package) package
logging.level.com.eshwar=DEBUG


#properties related to the circuit breaker for productService

# Percentage of failures to open the circuit
resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50

# Minimum calls before calculating failure rate
resilience4j.circuitbreaker.instances.productService.minimum-number-of-calls=5

# Number of calls to consider
resilience4j.circuitbreaker.instances.productService.sliding-window-size=10

# Type of sliding window (COUNT_BASED or TIME_BASED)
resilience4j.circuitbreaker.instances.productService.sliding-window-type=COUNT_BASED

# Time circuit stays OPEN before moving to HALF-OPEN
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s

# Number of calls allowed in HALF-OPEN state
resilience4j.circuitbreaker.instances.productService.permitted-number-of-calls-in-half-open-state=3

# Automatically move from OPEN to HALF-OPEN
resilience4j.circuitbreaker.instances.productService.automatic-transition-from-open-to-half-open-enabled=true

#properties related to the circuit breaker for inventoryService

# Percentage of failures to open the circuit
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50

# Minimum calls before calculating failure rate
resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=5

# Number of calls to consider
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=10

# Type of sliding window (COUNT_BASED or TIME_BASED)
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-type=COUNT_BASED

# Time circuit stays OPEN before moving to HALF-OPEN
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s

# Number of calls allowed in HALF-OPEN state
resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=3

# Automatically move from OPEN to HALF-OPEN
resilience4j.circuitbreaker.instances.inventoryService.automatic-transition-from-open-to-half-open-enabled=true


#properties related to the circuit breaker for paymentService

# Percentage of failures to open the circuit
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50

# Minimum calls before calculating failure rate
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5

# Number of calls to consider
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=10

# Type of sliding window (COUNT_BASED or TIME_BASED)
resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED

# Time circuit stays OPEN before moving to HALF-OPEN
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s

# Number of calls allowed in HALF-OPEN state
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3

# Automatically move from OPEN to HALF-OPEN
resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true

#properties related to the circuit breaker for notificationService

# Percentage of failures to open the circuit
resilience4j.circuitbreaker.instances.notificationService.failure-rate-threshold=50

# Minimum calls before calculating failure rate
resilience4j.circuitbreaker.instances.notificationService.minimum-number-of-calls=5

# Number of calls to consider
resilience4j.circuitbreaker.instances.notificationService.sliding-window-size=10

# Type of sliding window (COUNT_BASED or TIME_BASED)
resilience4j.circuitbreaker.instances.notificationService.sliding-window-type=COUNT_BASED

# Time circuit stays OPEN before moving to HALF-OPEN
resilience4j.circuitbreaker.instances.notificationService.wait-duration-in-open-state=10s

# Number of calls allowed in HALF-OPEN state
resilience4j.circuitbreaker.instances.notificationService.permitted-number-of-calls-in-half-open-state=3

# Automatically move from OPEN to HALF-OPEN
resilience4j.circuitbreaker.instances.notificationService.automatic-transition-from-open-to-half-open-enabled=true


#By default, Spring Boot exposes only a few endpoints. This property exposes all Actuator endpoints.
management.endpoints.web.exposure.include=*

#To get the Memory details using health actuator
management.endpoint.health.show-details=always

#Kafka broker address (where Kafka is running)
spring.kafka.bootstrap-servers=localhost:9092

#specifying the topic name
app.topic.name=order-topic

#properties for producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Show error message
spring.web.error.include-message=always

# Show validation/binding errors
spring.web.error.include-binding-errors=always

# Show stack trace in the response (for debugging only)
spring.web.error.include-stacktrace=always

#This helps include the exception type in the error response.
spring.web.error.include-exception=true

#It enables the /actuator/info endpoint to read the info.* properties
management.info.env.enabled=true

#Currect application details so that info actuator can display
info.app.name=Order Service
info.app.description=Order Microservice
info.app.version=1.0
info.app.author=Eshwar Reddy

