spring.application.name=PRODUCT-SERVICE
#this tells to connect to the config server which is running on the 8888 port no
spring.config.import=optional:configserver:http://localhost:8888

#specifying Logger File name
logging.file.name=c:/MicroServiceMiniProject/product-service_log4.txt

#specifying the logger level as debug for com.eshwar(root package) package
logging.level.com.eshwar=DEBUG

#By default, Spring Boot exposes only a few endpoints. This property exposes all Actuator endpoints.
management.endpoints.web.exposure.include=*

#It enables the /actuator/info endpoint to read the info.* properties
management.info.env.enabled=true

#Currect application details so that info actuator can display
info.app.name=Product Service
info.app.description=Product Microservice
info.app.version=1.0
info.app.author=Eshwar Reddy


#To get the Memory details using health actuator
management.endpoint.health.show-details=always
