spring.application.name=SpringBootMSProj14MiniProject-EurekaServerApp
#providing the embedded eureka server port no
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#specifying Logger File name
logging.file.name=c:/MicroServiceMiniProject/eureka_elk_log1.txt

#specifying the logger level as debug for com.eshwar(root package) package
logging.level.com.eshwar=DEBUG
