spring.application.name=API-GATEWAY
#This tells to connect to the config server which is running on the port no 8888
spring.config.import=optional:configserver:http://localhost:8888

#specifying Logger File name
logging.file.name=c:/MicroServiceMiniProject/apigateway_elk_log3.txt

#specifying the logger level as debug for com.eshwar(root package) package
logging.level.com.eshwar=DEBUG

#By default, Spring Boot exposes only a few endpoints. This property exposes all Actuator endpoints.
management.endpoints.web.exposure.include=*

#To get the Memory details using health actuator
management.endpoint.health.show-details=always


#It enables the /actuator/info endpoint to read the info.* properties
management.info.env.enabled=true

#Currect application details so that info actuator can display
info.app.name=API Gateway Service
info.app.description=API Gateway Microservice
info.app.version=1.0
info.app.author=Eshwar Reddy